export const FETCH_TOP_10_MOVIES_REQUEST = 'FETCH_TOP_10_MOVIES_REQUEST';
export const FETCH_TOP_10_MOVIES_SUCCESS = 'FETCH_TOP_10_MOVIES_SUCCESS';
export const FETCH_TOP_10_MOVIES_FAILURE = 'FETCH_TOP_10_MOVIES_FAILURE';

