export const FETCH_TOP_10_TV_SHOW_REQUEST = 'FETCH_TOP_10_TV_SHOW_REQUEST';
export const FETCH_TOP_10_TV_SHOW_SUCCESS = 'FETCH_TOP_10_TV_SHOW_SUCCESS';
export const FETCH_TOP_10_TV_SHOW_FAILURE = 'FETCH_TOP_10_TV_SHOW_FAILURE';

